platform :ios, '9.1'

target 'MathTouch_Unified' do
    pod 'MyScriptInteractiveInk-UIReferenceImplementation', :path => '../..'
    pod 'iosMath'
    pod 'SwiftSocket'
    pod 'SQLite.swift', '~> 0.11.5'
end
